### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by YakovAU** [Eyevinn/toolbox#1]
Hey.
Im attempting to use a compiled ffmpeg & SRT with Eyevinn Toolbox.

Upon trying any docker commands i get the following error: standard_init_linux.go:211: exec user process caused "exec format error"

With for example: docker run --rm -p 1234:1234/udp eyevinntechnology/toolbox-srtrx (my IP):9998 239.0.0.1:1234

Im using Lubuntu 19.10

Thanks for any assistance.

**Comment by birme** [comment]
Hi, it looks like you are missing the tag/version of the container image. Should be something like:

```
docker run --rm -p 1234:1234/udp eyevinntechnology/toolbox-srtrx:v0.1.0 (my IP):9998 239.0.0.1:1234
```

where `v0.1.0` was just an example.
