### ISSUE TITLE
SRT2RTMP - Passing stream key through from OBS for security and rebuilding purposes

### ISSUE THREAD

**Issue by codraziel** [Eyevinn/toolbox#12]
Is it possible to have the SRT2RTMP pass a Twitch/Youtube stream key from OBS onto the rtmp url(as can be done with an NGINX relay). This would be an extremely helpful for myself from a security perspective and also I'd like to recreate this for other local twitch streamers struggling with the same problem.

**Comment by Sgtfishtank** [comment]
Unfortunately we can not do what you are asking. The way the tool is built and its intended use makes this not feasible. The tool is designed to have one SRT-stream as an input and output to multiple RTMP-streams where the streams is not guaranteed to have the same stream key. You can add the stream-key at the end of the RTMP url and it will work. We don't really understand your use-case either. If you describe it better maybe we can help you some other way.

**Comment by codraziel** [comment]
Thank you for your response. My use case is simply streaming via SRT to a server overseas and then relaying that via RTMP to Twitch or YouTube. SRT2RTMP solves this perfectly with the one exception being that someone could theoretically take over my stream with nothing but the ip of my relay. Therefore I'd like to pass my stream key through the relay rather than have it always point to my stream key regardless of OBS settings. Additionally I'd like to help streamers in a similar position so simplifying it this way would assist in guiding less knowledgeable streamers. Either way this tool has been a game changer for my small twitch stream.

**Comment by DavidDuchovny** [comment]
I have the same problem but I would use it for RTMP2SRT. So I basically want to pass the incoming RTMP stream key to the SRT server without having to configure the server itself. It should be able to pass it or at least use the incoming stream key as part of the used SRT key. So the server would need to get the stream key, save it into a variable and then use it again in the output SRT stream.

Would this be easy an easy modification?

**Comment by FilipStadler** [comment]
> Thank you for your response. My use case is simply streaming via SRT to a server overseas and then relaying that via RTMP to Twitch or YouTube. 

 If you stream to maybe both twich and youtube they key is not the same keys and SRT is secure possible secure.
Have a look on https://github.com/datarhei/restreamer its not very fast using srt but usefull even if does not pass the key.
You can even mix rtmp and hls to youtube etc.
