### ISSUE TITLE
Instructions / Tutorial videos

### ISSUE THREAD

**Issue by amarmashruwala** [Eyevinn/toolbox#13]
Hello, 

Is there instructions or a video on how to install and use these tools. 
i understand that they need docker installed. 

Questions. 
1. Which operating systems can these work on? 
2. Can it work on a raspberry pi / Jetson Nano 
3. Do i fist install docker, next clone the URL - https://github.com/Eyevinn/toolbox.git
4. once i have done that do i simple run the docker command such as (docker run --rm -p 1234:1234/udp eyevinntechnology/toolbox-srt2rtmp:0.1.1 0.0.0.0:1234 <RTMPURL1> <RTMPURL2>)
thanks

**Comment by birme** [comment]
Hi, we don't have any instructions video on how to install and use these tools today. To try to answer your questions:

1. You should be able to run them on Linux, Windows and MacOS where Docker Engine is supported. Limitations apply on for example MacOS where you cannot run in host-mode but most of the instructions are assuming that
2. We have not verified that, but the community perhaps can answer that
3. Yes correct
4. Yes

Hope it answered your questions!
