### ISSUE TITLE
SRT TO RMTP

### ISSUE THREAD

**Issue by SNRSE** [Eyevinn/toolbox#3]
Hey i tried you srt to RMTP ccontainer. It works but still prints : 
12:57:30.540310/ffmpeg*E:SRT.d: epoll/update: IPE: update struck EID 1 which is NOT SUBSCRIBED to @105050122
is that normal ?

**Comment by mkdryden** [comment]
It is normal for libsrt built before [this PR](https://github.com/Haivision/srt/pull/1127). As far as I know, it doesn't cause any problems.

**Comment by birme** [comment]
Yes, exactly. I have planned to build a version with a newer build of libsrt but haven't got around to do so yet.
