### ISSUE TITLE
Minimal streaming example

### ISSUE THREAD

**Issue by Schizo** [Eyevinn/toolbox#5]
I was reading your [article](https://medium.com/@eyevinntechnology/using-ffmpeg-and-srt-to-transport-video-signal-to-the-cloud-7160960f846a) and pardon me if I'm not too familiar with the terminology, but I have hard times understanding how to create a minimal streaming example with `SRT`? 

My current setup that I want to switch to SRT is described as follows: 
**Sender:** 
`ffmpeg -f avfoundation -i "1:0" -an  -r 30 -vf scale=1280:720 -vcodec libx264 -crf 12 -preset ultrafast -tune zerolatency -threads 8 -thread_type slice -f  mpegts udp://192.168.1.5:1234`

**Receiver:**
The receiver was using a Player like VLC or MX Player by opening `udp://@192.168.1.5:1234`. 

How would I come up with a similar situation with `SRT`

Appreciate your help.

**Comment by birme** [comment]
Given that you have compiled ffmpeg with the SRT SDK you should be able to do this:
```
ffmpeg -f avfoundation -i "1:0" -an -r 30 -vf scale=1280:720 -vcodec libx264 -crf 12 -preset ultrafast -tune zerolatency -threads 8 -thread_type slice -f mpegts srt://192.168.1.5:1234?mode=listener
```

And in VLC
```
srt://@192.168.1.5:1234
```
